# Generated by Django 6.0.3 on 2026-03-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_customuser_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.publisher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader'), ('editor', 'Editor'), ('journalist', 'Journalist')], max_length=20),
        ),
    ]
