# Generated by Django 6.0.3 on 2026-03-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_customuser_publisher_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='journalists',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='news_app.publisher'),
        ),
    ]
